# Default values for:
  # crossplane
  # azureProvider
  # azureActiveDirectoryProvider
  # Kuberentes Secret (without data)
  # azureProviderConfig (which used for both Providers)



nameOverride: ""
fullnameOverride: ""


composition:
  enabled: true

crossplane:
  enabled: true
  metrikucs:
    # -- Expose Crossplane and RBAC Manager metrics endpoint.
    enabled: false

azureProvider:
  enabled: false
  package:
    path: xpkg.upbound.io/upbound/provider-azure #:v0.3.0
    version: v0.32.0


azureProviderAAD:
  enabled: false
  package:
    path:  xpkg.upbound.io/upbound/provider-azuread
    version: v0.8.0




#TODO: how to ensure that secret is created
azureProviderConfig:
  enabled: true
  secret:
    enable: false
    data: $AZURE_PROVIDER_CONFIG_SECRET # created with: 'az ad sp create-for-rbac --sdk-auth --role Owner --scopes /subscriptions/<Subscription ID>'
    namespace: crossplane-system #TODO should that be even forced?
    name: azure-secret
    key: creds # needed for SecretRef in azureProviderConfig


resourceGroup:
  enabled: false
  name: example-rg-try2
  location: Germany West Central
  providerConfig:
    name: default






