{{- if .Values.azureProviderConfig.enabled -}}
{{ $azureProvicerConfigSecret := .Values.azureProviderConfig.secret}}
apiVersion: azure.upbound.io/v1beta1
metadata:
  name: default
  dependsOn:
    - apiGroup: pkg.crossplane.io/v1
      kind: Provider
      name: upbound-provider-azure
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef:
      name: {{ $azureProvicerConfigSecret.name}}
      namespace: {{ $azureProvicerConfigSecret.namespace}}
      key: {{ $azureProvicerConfigSecret.key}}
{{- end -}}