{{- if .Values.azureProviderConfig.enabled}}
apiVersion: azure.upbound.io/v1beta1
metadata:
  name: default
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef: {{- .Values.azureProviderConfig.secretRef | toYaml | nindent 6 -}}
{{- end}}