{{- if .Values.azureProviderConfig.enabled -}}
{{ $azureProvicerConfigSecret := .Values.azureProviderConfig.secret}}
apiVersion: azure.upbound.io/v1beta1
metadata:
  name: default
  dependsOn:
    - apiGroup: azure.crossplane.io
      kind: CustomResourceDefinition
      name: Provider
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef:
      name: {{ $azureProvicerConfigSecret.name}}
      namespace: {{ $azureProvicerConfigSecret.namespace}}
      key: {{ $azureProvicerConfigSecret.key}}
  dependsOn:
    - provider: {{ .Values.azureProvider.package.path}}
      version:  {{ .Values.azureProvider.package.version}}
{{- end -}}