{{- if .Values.azureProviderConfig.enabled -}}
{{ $azureProvicerConfigSecret := .Values.azureProviderConfig.secret}}
apiVersion: configurations.pkg.crossplane.io
metadata:
  name: default
  dependsOn:
    - apiGroup: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: providers.pkg.crossplane.io
    - apiGroup: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: configurations.pkg.crossplane.io
    - apiGroup: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: azure.crossplane.io
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef:
      name: {{ $azureProvicerConfigSecret.name}}
      namespace: {{ $azureProvicerConfigSecret.namespace}}
      key: {{ $azureProvicerConfigSecret.key}}
  # dependsOn:
  #   - provider: {{ .Values.azureProvider.package.path}}
  #     version:  {{ .Values.azureProvider.package.version}}
{{- end -}}