{{- if .Values.azureProviderAAD.enabled}}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azuread
spec:
  package: "{{ template "azureADProvider" . }}"
  dependsOn:
    - provider: {{ .Values.azureProvider.package.path}}
      version:  {{ .Values.azureProvider.package.version}}
{{- end}}