{{- if .Values.composition.enabled }}
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xproviderandconfigs.azureproviderwithconfig.example.org
spec:
  group: azureproviderwithconfig.example.org
  names:
    kind: XProviderAndConfig
    plural: xproviderandconfigs
  claimNames:
    kind: ProviderAndConfig
    plural: providerandconfigs
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                required:
                - storageGB
            required:
            - parameters
---
apiVersion: azureproviderwithconfig.example.org/v1alpha1
kind: ProviderAndConfig
metadata:
  # Claims are namespaced, unlike XRs.
  namespace: crossplane-system
  name: my-composite
  annotations:
    # The external name annotation has special meaning in Crossplane. When a
    # claim creates an XR its external name will automatically be propagated to
    # the XR. Whether and how the external name is propagated to the resources
    # the XR composes is up to its Composition.
    crossplane.io/external-name: my-composite-externamename
spec:
  # resources:
  #   - name: provider-azure
  #     version: v0.32.0
  #     kind: Provider
  #   - name: azure-provider-config
  #     kind: ProviderConfig
  parameters:
    storageGB: 20
  compositionRef:
    name: production
  writeConnectionSecretToRef:
    name: my-db-connection-details
---

# apiVersion: apiextensions.crossplane.io/v1
# kind: Composition
# metadata:
#   name: azure-composition
# spec:
#   compositeTypeRef:
#     apiVersion: compose.crossplane.io/v1
#     kind: Composition
#   resources:
#     - name: provider-azure
#       version: v0.32.0
#       kind: Provider
#     - name: azure-provider-config
#       kind: ProviderConfig

# ---
# apiVersion: compose.crossplane.io/v1
# kind: CompositionClaim
# metadata:
#   name: azure-composition-claim
# spec:
#   compositionRef:
#     name: azure-composition
#   resources:
#     - name: provider-azure
#       kind: Provider
#       properties:
#         package: "xpkg.upbound.io/upbound/provider-azure:v0.32.0"
#     - name: azure-provider-config
#       kind: ProviderConfig
#       properties:
#         credentials:
#           source: Secret
#           secretRef:
#             name: azure-secret
#             namespace: crossplane-system
#             key: creds

#---
# apiVersion: apiextensions.crossplane.io
# kind: Composition
# metadata:
#   name: azure-provider-with-config
# spec:
#   resources:
#     - name: provider-azure
#       kind: Provider
#       version: v0.32.0
#       spec:
#         package: "xpkg.upbound.io/upbound/provider-azure:v0.32.0"
#     - name: azure-provider-config
#       kind: ProviderConfig
#       spec:
#         credentials:
#           source: Secret
#           secretRef:
#             name: azure-secret
#             namespace: crossplane-system
#             key: creds
{{- end }}