{{ $azureProviderConfigSecret := .Values.azureProviderConfig.secret }}
{{- if $azureProviderConfigSecret.enable -}}
apiVersion: v1
kind: Secret
data:
  creds: {{ $azureProviderConfigSecret.data}}
metadata:
  name: {{ $azureProviderConfigSecret.name }}
  namespace: {{ $azureProviderConfigSecret.namespace }}
type: Opaque
{{- end -}}